## Array Manipulation Routines

In [26]:
import numpy as np

### numpy.stack
Join a sequence of arrays along a new axis.

The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension.

In [50]:
A = []
a1 = np.random.randint(low=1, high=9, size=(2, 3))
a2 = np.random.randint(low=1, high=9, size=(2, 3))

A.append(a1)
A.append(a2)
print(type(A))
print(np.stack(A))
print(np.stack(A).shape)
print(type(np.stack(A)))

<class 'list'>
[[[6 4 2]
  [8 4 8]]

 [[7 8 3]
  [5 6 1]]]
(2, 2, 3)
<class 'numpy.ndarray'>


In [54]:
arrays = [np.random.randint(low=1, high=9, size=(2, 3)) for _ in range(3)]
print(arrays)
np.stack(arrays)

[array([[6, 5, 7],
       [7, 8, 3]]), array([[6, 8, 5],
       [1, 8, 4]]), array([[7, 6, 3],
       [4, 6, 8]])]


array([[[6, 5, 7],
        [7, 8, 3]],

       [[6, 8, 5],
        [1, 8, 4]],

       [[7, 6, 3],
        [4, 6, 8]]])

In [34]:
A = np.stack(arrays)
print(A)

[[[ 1.02415395  1.06195447 -0.67279345]
  [ 0.11905508 -0.71272673 -1.73564088]]

 [[ 0.72025567 -1.53912195 -0.00404676]
  [ 0.74579066 -1.27777705 -0.92571078]]

 [[-0.81351448  1.56290273  0.38613568]
  [-0.12421028  0.46788452 -0.59213913]]]


In [70]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b))
print(np.stack((a, b)).shape)

(2, 3)


In [61]:
print(np.stack((a, b), axis=0))
print(type(np.stack((a, b), axis=0)))
np.stack((a, b), axis=0).shape

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


(2, 3)

In [62]:
print(np.stack((a, b), axis=1))
print(type(np.stack((a, b), axis=1)))
np.stack((a, b), axis=1).shape

[[1 4]
 [2 5]
 [3 6]]
<class 'numpy.ndarray'>


(3, 2)

In [63]:
print(np.stack((a, b), axis=2))
print(type(np.stack((a, b), axis=2)))
np.stack((a, b), axis=2).shape

AxisError: axis 2 is out of bounds for array of dimension 2

In [81]:
arrays = [np.random.randn(2, 3) for _ in range(4)]
print(arrays)

[array([[ 0.07159973, -0.48856014,  1.62336408],
       [-0.41684332,  0.68148062, -0.25701735]]), array([[ 0.71317265,  1.66406368,  1.32941461],
       [-0.4021398 , -0.46050001,  1.15684989]]), array([[-0.8173173 , -0.99509961,  0.22247641],
       [ 0.50398027, -0.47412464,  0.18012429]]), array([[1.54607815, 0.55664008, 1.25390788],
       [1.21853407, 0.28192985, 1.36843743]])]


In [82]:
print(np.stack(arrays, axis=0).shape)
print(np.stack(arrays, axis=0))

(4, 2, 3)
[[[ 0.07159973 -0.48856014  1.62336408]
  [-0.41684332  0.68148062 -0.25701735]]

 [[ 0.71317265  1.66406368  1.32941461]
  [-0.4021398  -0.46050001  1.15684989]]

 [[-0.8173173  -0.99509961  0.22247641]
  [ 0.50398027 -0.47412464  0.18012429]]

 [[ 1.54607815  0.55664008  1.25390788]
  [ 1.21853407  0.28192985  1.36843743]]]


In [83]:
print(np.stack(arrays, axis=1).shape)
print(np.stack(arrays, axis=1))

(2, 4, 3)
[[[ 0.07159973 -0.48856014  1.62336408]
  [ 0.71317265  1.66406368  1.32941461]
  [-0.8173173  -0.99509961  0.22247641]
  [ 1.54607815  0.55664008  1.25390788]]

 [[-0.41684332  0.68148062 -0.25701735]
  [-0.4021398  -0.46050001  1.15684989]
  [ 0.50398027 -0.47412464  0.18012429]
  [ 1.21853407  0.28192985  1.36843743]]]


In [80]:
print(np.stack(arrays, axis=2).shape)
print(np.stack(arrays, axis=2))

(2, 3, 4)
[[[-0.5672631  -0.37629083  0.18014264  0.56859955]
  [-2.08531209 -0.26873099 -1.43504901 -0.80262724]
  [ 0.83745819  0.01875236  0.90773745  0.43049006]]

 [[-0.31196546 -1.14015968 -1.95866458 -0.50823003]
  [-0.18556525 -1.0770908  -0.48372291  1.34639839]
  [ 0.6974311  -0.31975271  0.8736552   0.53624199]]]


In [68]:
np.stack(arrays, axis=3).shape

AxisError: axis 3 is out of bounds for array of dimension 3